const userTypes = {
    START_EMAIL_SIGN_IN:'START_EMAIL_SIGN_IN',
    SUCCESS_SIGN_IN: 'SUCCESS_SIGN_IN',
    USER_SESSION:'USER_SESSION',
    USER_SIGN_OUT_START: 'USER_SIGN_OUT_START',
    USER_SIGN_OUT_SUCCESS: 'USER_SIGN_OUT_SUCCESS',
    //ERROR_SIGN_IN: 'ERROR_SIGN_IN',
    USER_SIGN_UP_START: 'USER_SIGN_UP_START',
    PASSWORD_RESET_START: ' PASSWORD_RESET_START',
    START_GOOGLE_SIGN_IN: 'START_GOOGLE_SIGN_IN',
    SUCCESS_PASSWORD_RESET: 'SUCCESS_PASSWORD_RESET',
    USER_ERROR: 'USER_ERROR',
    USER_RESET_STATE:'USER_RESET_STATE',

    //SET_CURRENT_USER: 'SET_CURRENT_USER',
    //SUCCESS_SIGN_UP: 'SUCCESS_SIGN_UP',
    //ERROR_SIGN_UP: 'ERROR_SIGN_UP',
    //SUCCESS_PASSWORD_RESET: 'SUCCESS_PASSWORD_RESET',
    //ERROR_PASSWORD_RESET: 'ERROR_PASSWORD_RESET',
    //AUTHENTICATION_RESET: 'AUTHENTICATION_RESET'
    
};

export default userTypes;